# Generated by Django 6.0.5 on 2026-05-22 08:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, help_text='Ej: fas fa-hamburger, fas fa-fire', max_length=60, verbose_name='Ícono')),
                ('color', models.CharField(default='#fb8500', help_text='Color hexadecimal para distinguir la categoría', max_length=20, verbose_name='Color')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=140, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de venta')),
                ('imagen', models.FileField(blank=True, help_text='Imagen del producto (JPG/PNG).', null=True, upload_to='productos/', verbose_name='Imagen')),
                ('activo', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria__orden', 'nombre'],
                'indexes': [models.Index(fields=['activo', 'categoria'], name='products_pr_activo_1a45f6_idx')],
            },
        ),
    ]
