# Generated by Django 6.0.5 on 2026-05-22 08:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número')),
                ('cliente', models.CharField(blank=True, max_length=120, verbose_name='Cliente')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=15, verbose_name='Estado')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('qr', 'QR')], default='efectivo', max_length=20, verbose_name='Método de pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('notas', models.TextField(blank=True, verbose_name='Notas especiales')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('nota', models.CharField(blank=True, max_length=200, verbose_name='Nota')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Detalle de pedido',
                'verbose_name_plural': 'Detalles de pedido',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['estado', '-creado'], name='orders_orde_estado_29bc84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['vendedor', '-creado'], name='orders_orde_vendedo_ada4be_idx'),
        ),
    ]
