# Generated by Django 6.0.5 on 2026-05-23 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='iva',
        ),
    ]
