# Generated by Django 5.2.7 on 2026-05-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clave_acceso',
            field=models.CharField(blank=True, max_length=49, null=True, verbose_name='Clave de acceso'),
        ),
        migrations.AddField(
            model_name='order',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='identificacion',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identificación'),
        ),
        migrations.AddField(
            model_name='order',
            name='secuencial_factura',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Secuencial de factura'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_cero',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Subtotal Cero'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Subtotal IVA'),
        ),
        migrations.AddField(
            model_name='order',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='order',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor Final')], max_length=2, null=True, verbose_name='Tipo de identificación'),
        ),
        migrations.AddField(
            model_name='order',
            name='valor_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor IVA'),
        ),
    ]
